## Controle — vídeos cadastrados

A tabela abaixo é a fila de vídeos monitorados. Cada registro define se o vídeo está ativo, sua prioridade e o intervalo entre atualizações.

In [1]:
%sql
select *
from youtube_lakehouse.control.video_targets;

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[video_id: string, is_active: boolean, priority: int, refresh_interval_hours: int, created_at: timestamp, updated_at: timestamp]

## Controle — estado de processamento

Este estado mostra a última tentativa, o último sucesso, a próxima atualização prevista e eventuais erros por vídeo.

In [2]:
%sql
SELECT *
FROM youtube_lakehouse.control.video_processing_state;

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[video_id: string, status: string, first_processed_at: timestamp, claimed_at: timestamp, last_attempt_at: timestamp, last_succeeded_at: timestamp, next_refresh_at: timestamp, attempt_count: bigint, last_ingestion_id: string, error_message: string]

## Controle — execuções de ingestão

Aqui ficam o início, fim, status, canais observados e erros globais de cada execução do pipeline.

In [3]:
%sql
SELECT *
FROM youtube_lakehouse.control.ingestion_runs;

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[ingestion_id: string, channel_handle: string, channel_name: string, started_at: timestamp, ended_at: timestamp, status: string, error_message: string]

## Raw — respostas originais da API

Esta tabela preserva os parâmetros sem a chave e o JSON original de cada resposta bem-sucedida da YouTube Data API.

In [4]:
%sql
SELECT *
FROM youtube_lakehouse.raw.api_responses;

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[ingestion_id: string, resource: string, request_params_json: string, response_json: string, received_at: timestamp]

## Silver — canais

Estado atual normalizado dos canais: metadados públicos e contagens mais recentes.

In [6]:
%sql
SELECT channel_id, title, view_count, subscriber_count, video_count, ingested_at
FROM youtube_lakehouse.silver.channels;

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[channel_id: string, title: string, view_count: bigint, subscriber_count: bigint, video_count: bigint, ingested_at: timestamp]

## Silver — vídeos

Estado atual normalizado dos vídeos, incluindo título, metadados e métricas públicas atuais.

In [8]:
%sql
SELECT video_id, channel_id, title, published_at, view_count, like_count, comment_count, ingested_at
FROM youtube_lakehouse.silver.videos;

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[video_id: string, channel_id: string, title: string, published_at: string, view_count: bigint, like_count: bigint, comment_count: bigint, ingested_at: timestamp]

## Silver — comentários

Comentários de primeiro nível conhecidos, atualizados pelo identificador do comentário.

In [14]:
%sql
SELECT video_id, thread_id, comment_id, parent_id, author_name, text, like_count, reply_count, published_at, updated_at, ingested_at
FROM youtube_lakehouse.silver.comments
LIMIT 5;

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[video_id: string, thread_id: string, comment_id: string, parent_id: string, author_name: string, text: string, like_count: bigint, reply_count: bigint, published_at: string, updated_at: string, ingested_at: timestamp]

## Silver — respostas aos comentários

Respostas conhecidas dos comentários de primeiro nível, vinculadas ao comentário pai.

In [18]:
%sql
SELECT video_id, comment_id, parent_id, author_name, text, like_count, published_at, updated_at, ingested_at
FROM youtube_lakehouse.silver.replies
LIMIT 5;

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[video_id: string, comment_id: string, parent_id: string, author_name: string, text: string, like_count: bigint, published_at: string, updated_at: string, ingested_at: timestamp]

## Silver — snapshots de canais

Histórico imutável das métricas públicas dos canais por execução de ingestão.

In [19]:
%sql
SELECT *
FROM youtube_lakehouse.silver.channel_snapshots;

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[channel_id: string, ingestion_id: string, collected_at: timestamp, view_count: bigint, subscriber_count: bigint, video_count: bigint]

## Silver — snapshots de vídeos

Histórico imutável de visualizações, curtidas e quantidade de comentários por vídeo e execução.

In [20]:
%sql
SELECT *
FROM youtube_lakehouse.silver.video_snapshots;

HBox(children=(IntProgress(value=0, bar_style='success'), Label(value='')))

DataFrame[video_id: string, ingestion_id: string, collected_at: timestamp, view_count: bigint, like_count: bigint, comment_count: bigint]